#!/usr/bin/env python3
"""Regenerate the tool catalog in docs/TOOLS.md from the live registry (#36).

The server is the source of truth: this script imports ``server`` at
``MCP_ACCESS_LEVEL=full`` (every tool registered), reads each tool's access
tier from ``core.access`` and its capabilities from ``core.capabilities``, and
rewrites the block between ``<!-- tools:begin -->`` and ``<!-- tools:end -->``.
``tests/test_tool_docs.py`` fails when the file is stale or a tool is missing.

No token or network is needed: target settings get placeholders when unset.

Usage (inside the image, like the rest of the tooling):
    python3 scripts/gen_tool_docs.py            # rewrite docs/TOOLS.md
    python3 scripts/gen_tool_docs.py --check    # exit 1 if it would change
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOC = ROOT / "docs" / "TOOLS.md"
BEGIN, END = "<!-- tools:begin -->", "<!-- tools:end -->"

# Module (tools/<category>/...) → section title, in catalog order.
SECTIONS = {
    "meta": "Diagnostics, stats and pull requests",
    "discovery": "Discovery",
    "projects": "Project board and provisioning",
    "fields": "Fields, estimates, labels and milestones",
    "issues": "Issues",
    "bulk": "Bulk operations",
    "pull_requests": "PR ↔ issue lifecycle",
    "ci": "CI / GitHub Actions",
    "planning": "Planning and workflows",
    "repositories": "Repositories",
    "repository_content": "Repository contents and governed commits",
    "deletes": "Permanent deletes (MCP_ACCESS_LEVEL=full)",
    "capability_suite": "Extended capability suite",
}


def _category(fn) -> str:
    module = getattr(fn, "__module__", "") or ""
    parts = module.split(".")
    if module.endswith("capability_suite"):
        return "capability_suite"
    if parts[-1] == "deletes":
        return "deletes"
    if parts[-1] == "project_provisioning":
        return "projects"
    if len(parts) >= 2 and parts[0] == "tools":
        return parts[1] if len(parts) > 2 else parts[1].removesuffix(".py")
    return "meta"


def _summary(fn) -> str:
    doc = (getattr(fn, "__doc__", "") or "").strip().splitlines()
    text = doc[0].strip() if doc else ""
    return text.replace("|", "\\|")


def collect() -> list[dict]:
    """Every tool the server registers at `full`, with tier and capabilities."""
    os.environ["MCP_ACCESS_LEVEL"] = "full"
    for key, value in (
        ("GH_PROJECT_ORG_NAME", "example-org"),
        ("GH_PROJECT_REPO_NAME", "example-repo"),
        ("GH_PROJECT_PROJECT_NUMBER", "1"),
    ):
        os.environ.setdefault(key, value)
    sys.path.insert(0, str(ROOT))

    from core.access import classify
    from core.capabilities import TOOL_CAPABILITIES
    from core.config import get_settings

    get_settings.cache_clear()
    import server

    rows = []
    for fn in server._ALL_TOOLS:
        name = "complete_issue" if fn is server.complete_issue_workflow else fn.__name__
        caps = sorted(c.value for c in TOOL_CAPABILITIES.get(name, ()))
        rows.append(
            {
                "name": name,
                "category": _category(fn),
                "tier": classify(name).value,
                "capabilities": ", ".join(f"`{c}`" for c in caps) or "—",
                "summary": _summary(fn),
            }
        )
    return rows


def render(rows: list[dict]) -> str:
    order = list(SECTIONS)
    rows = sorted(rows, key=lambda r: (order.index(r["category"]) if r["category"] in order else len(order), r["name"]))
    lines = [BEGIN, "", f"_{len(rows)} tools at `MCP_ACCESS_LEVEL=full`, generated by `scripts/gen_tool_docs.py`._"]
    current = None
    for row in rows:
        if row["category"] != current:
            current = row["category"]
            lines += [
                "",
                f"### {SECTIONS.get(current, current)}",
                "",
                "| Tool | Access | Capabilities | Summary |",
                "|---|---|---|---|",
            ]
        lines.append(f"| `{row['name']}` | {row['tier']} | {row['capabilities']} | {row['summary']} |")
    lines += ["", END]
    return "\n".join(lines)


def updated_text() -> tuple[str, str]:
    text = DOC.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        raise SystemExit(f"error: markers missing in {DOC}")
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    return text, head + render(collect()) + tail


def main(argv: list[str]) -> int:
    current, updated = updated_text()
    if "--check" in argv:
        if updated != current:
            print("docs/TOOLS.md is stale: run scripts/gen_tool_docs.py", file=sys.stderr)
            return 1
        return 0
    DOC.write_text(updated, encoding="utf-8")
    print(f"updated {DOC.relative_to(ROOT)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
